# coding: utf-8

# flake8: noqa

"""
    Data Modelling Storage Service

    API for basic data modelling interaction

    The version of the OpenAPI document: 1.23.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AccessControlApi",
    "AttributeApi",
    "BlobApi",
    "BlueprintApi",
    "DatasourceApi",
    "DefaultApi",
    "DocumentApi",
    "EntityApi",
    "ExportApi",
    "FileApi",
    "HealthCheckApi",
    "LookupTableApi",
    "MetaApi",
    "PersonalAccessTokenApi",
    "SearchApi",
    "WhoamiApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccessControlList",
    "AccessLevel",
    "DataSourceInformation",
    "DataSourceRequest",
    "Dependency",
    "Entity",
    "ErrorResponse",
    "ExportMetaResponse",
    "GetAttributeResponse",
    "GetBlueprintResponse",
    "InitialuirecipesValue",
    "Lookup",
    "PATData",
    "Recipe",
    "RecipeAttribute",
    "Repository",
    "RepositoryType",
    "StorageAttribute",
    "StorageDataTypes",
    "StorageRecipe",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from dm_cli.dmss_api.api.access_control_api import AccessControlApi as AccessControlApi
    from dm_cli.dmss_api.api.attribute_api import AttributeApi as AttributeApi
    from dm_cli.dmss_api.api.blob_api import BlobApi as BlobApi
    from dm_cli.dmss_api.api.blueprint_api import BlueprintApi as BlueprintApi
    from dm_cli.dmss_api.api.datasource_api import DatasourceApi as DatasourceApi
    from dm_cli.dmss_api.api.default_api import DefaultApi as DefaultApi
    from dm_cli.dmss_api.api.document_api import DocumentApi as DocumentApi
    from dm_cli.dmss_api.api.entity_api import EntityApi as EntityApi
    from dm_cli.dmss_api.api.export_api import ExportApi as ExportApi
    from dm_cli.dmss_api.api.file_api import FileApi as FileApi
    from dm_cli.dmss_api.api.health_check_api import HealthCheckApi as HealthCheckApi
    from dm_cli.dmss_api.api.lookup_table_api import LookupTableApi as LookupTableApi
    from dm_cli.dmss_api.api.meta_api import MetaApi as MetaApi
    from dm_cli.dmss_api.api.personal_access_token_api import PersonalAccessTokenApi as PersonalAccessTokenApi
    from dm_cli.dmss_api.api.search_api import SearchApi as SearchApi
    from dm_cli.dmss_api.api.whoami_api import WhoamiApi as WhoamiApi
    
    # import ApiClient
    from dm_cli.dmss_api.api_response import ApiResponse as ApiResponse
    from dm_cli.dmss_api.api_client import ApiClient as ApiClient
    from dm_cli.dmss_api.configuration import Configuration as Configuration
    from dm_cli.dmss_api.exceptions import OpenApiException as OpenApiException
    from dm_cli.dmss_api.exceptions import ApiTypeError as ApiTypeError
    from dm_cli.dmss_api.exceptions import ApiValueError as ApiValueError
    from dm_cli.dmss_api.exceptions import ApiKeyError as ApiKeyError
    from dm_cli.dmss_api.exceptions import ApiAttributeError as ApiAttributeError
    from dm_cli.dmss_api.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from dm_cli.dmss_api.models.access_control_list import AccessControlList as AccessControlList
    from dm_cli.dmss_api.models.access_level import AccessLevel as AccessLevel
    from dm_cli.dmss_api.models.data_source_information import DataSourceInformation as DataSourceInformation
    from dm_cli.dmss_api.models.data_source_request import DataSourceRequest as DataSourceRequest
    from dm_cli.dmss_api.models.dependency import Dependency as Dependency
    from dm_cli.dmss_api.models.entity import Entity as Entity
    from dm_cli.dmss_api.models.error_response import ErrorResponse as ErrorResponse
    from dm_cli.dmss_api.models.export_meta_response import ExportMetaResponse as ExportMetaResponse
    from dm_cli.dmss_api.models.get_attribute_response import GetAttributeResponse as GetAttributeResponse
    from dm_cli.dmss_api.models.get_blueprint_response import GetBlueprintResponse as GetBlueprintResponse
    from dm_cli.dmss_api.models.initialuirecipes_value import InitialuirecipesValue as InitialuirecipesValue
    from dm_cli.dmss_api.models.lookup import Lookup as Lookup
    from dm_cli.dmss_api.models.pat_data import PATData as PATData
    from dm_cli.dmss_api.models.recipe import Recipe as Recipe
    from dm_cli.dmss_api.models.recipe_attribute import RecipeAttribute as RecipeAttribute
    from dm_cli.dmss_api.models.repository import Repository as Repository
    from dm_cli.dmss_api.models.repository_type import RepositoryType as RepositoryType
    from dm_cli.dmss_api.models.storage_attribute import StorageAttribute as StorageAttribute
    from dm_cli.dmss_api.models.storage_data_types import StorageDataTypes as StorageDataTypes
    from dm_cli.dmss_api.models.storage_recipe import StorageRecipe as StorageRecipe
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from dm_cli.dmss_api.api.access_control_api import AccessControlApi as AccessControlApi
from dm_cli.dmss_api.api.attribute_api import AttributeApi as AttributeApi
from dm_cli.dmss_api.api.blob_api import BlobApi as BlobApi
from dm_cli.dmss_api.api.blueprint_api import BlueprintApi as BlueprintApi
from dm_cli.dmss_api.api.datasource_api import DatasourceApi as DatasourceApi
from dm_cli.dmss_api.api.default_api import DefaultApi as DefaultApi
from dm_cli.dmss_api.api.document_api import DocumentApi as DocumentApi
from dm_cli.dmss_api.api.entity_api import EntityApi as EntityApi
from dm_cli.dmss_api.api.export_api import ExportApi as ExportApi
from dm_cli.dmss_api.api.file_api import FileApi as FileApi
from dm_cli.dmss_api.api.health_check_api import HealthCheckApi as HealthCheckApi
from dm_cli.dmss_api.api.lookup_table_api import LookupTableApi as LookupTableApi
from dm_cli.dmss_api.api.meta_api import MetaApi as MetaApi
from dm_cli.dmss_api.api.personal_access_token_api import PersonalAccessTokenApi as PersonalAccessTokenApi
from dm_cli.dmss_api.api.search_api import SearchApi as SearchApi
from dm_cli.dmss_api.api.whoami_api import WhoamiApi as WhoamiApi

# import ApiClient
from dm_cli.dmss_api.api_response import ApiResponse as ApiResponse
from dm_cli.dmss_api.api_client import ApiClient as ApiClient
from dm_cli.dmss_api.configuration import Configuration as Configuration
from dm_cli.dmss_api.exceptions import OpenApiException as OpenApiException
from dm_cli.dmss_api.exceptions import ApiTypeError as ApiTypeError
from dm_cli.dmss_api.exceptions import ApiValueError as ApiValueError
from dm_cli.dmss_api.exceptions import ApiKeyError as ApiKeyError
from dm_cli.dmss_api.exceptions import ApiAttributeError as ApiAttributeError
from dm_cli.dmss_api.exceptions import ApiException as ApiException

# import models into sdk package
from dm_cli.dmss_api.models.access_control_list import AccessControlList as AccessControlList
from dm_cli.dmss_api.models.access_level import AccessLevel as AccessLevel
from dm_cli.dmss_api.models.data_source_information import DataSourceInformation as DataSourceInformation
from dm_cli.dmss_api.models.data_source_request import DataSourceRequest as DataSourceRequest
from dm_cli.dmss_api.models.dependency import Dependency as Dependency
from dm_cli.dmss_api.models.entity import Entity as Entity
from dm_cli.dmss_api.models.error_response import ErrorResponse as ErrorResponse
from dm_cli.dmss_api.models.export_meta_response import ExportMetaResponse as ExportMetaResponse
from dm_cli.dmss_api.models.get_attribute_response import GetAttributeResponse as GetAttributeResponse
from dm_cli.dmss_api.models.get_blueprint_response import GetBlueprintResponse as GetBlueprintResponse
from dm_cli.dmss_api.models.initialuirecipes_value import InitialuirecipesValue as InitialuirecipesValue
from dm_cli.dmss_api.models.lookup import Lookup as Lookup
from dm_cli.dmss_api.models.pat_data import PATData as PATData
from dm_cli.dmss_api.models.recipe import Recipe as Recipe
from dm_cli.dmss_api.models.recipe_attribute import RecipeAttribute as RecipeAttribute
from dm_cli.dmss_api.models.repository import Repository as Repository
from dm_cli.dmss_api.models.repository_type import RepositoryType as RepositoryType
from dm_cli.dmss_api.models.storage_attribute import StorageAttribute as StorageAttribute
from dm_cli.dmss_api.models.storage_data_types import StorageDataTypes as StorageDataTypes
from dm_cli.dmss_api.models.storage_recipe import StorageRecipe as StorageRecipe

""",
            name=__name__,
            doc=__doc__,
        )
    )
