repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
        language_version: python3.10
      - id: check-merge-conflict
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: detect-private-key

  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.10
        files: ^app/.*\.py$
        additional_dependencies: ["click==8.0.4"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: [-l, --recursive, -x, tests, --skip, B311]
        files: ^app/.*\.py$


  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        files: ^app/.*\.py$

  - repo: https://gitlab.com/pycqa/flake8
    rev: "5.0.0"
    hooks:
      - id: flake8
        files: ^app/.*\.py$
        additional_dependencies:
          - flake8-print==5.0.0
          - flake8-docstrings==1.6.0
        args:
          [
            "--max-line-length=160",
            "--max-complexity=18",
            "--select=B,C,D,E,F,W,T4,T,B9",
            "--ignore=E203,E266,E501,W503,D100,D402",
            "--docstring-convention=pep257",
            "--per-file-ignores=tests/*:D"
          ]
