default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        language_version: python3.11
      - id: check-merge-conflict
      - id: check-yaml
      - id: trailing-whitespace
        exclude: ^.*\.(lock)$||^docs\/
      - id: end-of-file-fixer
        exclude: ^.*\.(lock)$||^docs\/
      - id: mixed-line-ending
        exclude: ^.*\.(lock)$||^docs\/
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          [--autofix, --no-sort-keys, "--top-keys=_id,name,type,description"]
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.11
        files: .*\.py$
        additional_dependencies: ["click==8.0.4"]
        exclude: ^dm_cli/dmss_api/
        args:
          - --line-length=119

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-l, --recursive, -x, tests, --skip, B311]
        files: ^.*\.py$
        exclude: ^dm_cli/dmss_api/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        files: ^.*\.py$
        exclude: ^dm_cli/dmss_api/
        args: ["--profile=black"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^./dm_cli/.*\.py$
        exclude: ^dm_cli/dmss_api/
        additional_dependencies:
          - flake8-print==5.0.0
          - flake8-docstrings==1.6.0
        args:
          [
            "--verbose",
            "--max-line-length=119",
            "--max-complexity=18",
            "--select=B,C,D,E,F,W,T4,T,B9",
            "--ignore=D100, D101, D102, D103, D104, D105, D107, D400, D401, T201",
            "--docstring-convention=pep257",
            "--per-file-ignores=tests/*:D",
          ]
