# coding: utf-8

"""
    Data Modelling Storage Service

    API for basic data modelling interaction  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from dm_cli.dmss_api.paths.api_blobs_data_source_id_blob_id.get import BlobGetById
from dm_cli.dmss_api.paths.api_blobs_data_source_id_blob_id.put import BlobUpload


class BlobApi(
    BlobGetById,
    BlobUpload,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
