# coding: utf-8

"""
    Data Modelling Storage Service

    API for basic data modelling interaction  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from dm_cli.dmss_api.paths.api_documents_absolute_ref.post import DocumentAdd
from dm_cli.dmss_api.paths.api_documents_data_source_id_add_raw.post import DocumentAddSimple
from dm_cli.dmss_api.paths.api_documents_path_reference_add_to_path.post import DocumentAddToPath
from dm_cli.dmss_api.paths.api_documents_id_reference.get import DocumentGetById
from dm_cli.dmss_api.paths.api_documents_by_path_absolute_path.get import DocumentGetByPath
from dm_cli.dmss_api.paths.api_documents_data_source_id_dotted_id.delete import DocumentRemove
from dm_cli.dmss_api.paths.api_documents_data_source_id_remove_by_path_directory.delete import DocumentRemoveByPath
from dm_cli.dmss_api.paths.api_documents_data_source_id_document_id.put import DocumentUpdate


class DocumentApi(
    DocumentAdd,
    DocumentAddSimple,
    DocumentAddToPath,
    DocumentGetById,
    DocumentGetByPath,
    DocumentRemove,
    DocumentRemoveByPath,
    DocumentUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
