# coding: utf-8

"""
    Data Modelling Storage Service

    API for basic data modelling interaction  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from dm_cli.dmss_api.paths.api_token.post import TokenCreate
from dm_cli.dmss_api.paths.api_token_token_id.delete import TokenDelete
from dm_cli.dmss_api.paths.api_token.get import TokenListAll


class PersonalAccessTokenApi(
    TokenCreate,
    TokenDelete,
    TokenListAll,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
