import json
import re
from typing import Any, Callable

import typer
from rich.console import Console
from rich.text import Text
from tenacity import (
    retry,
    retry_if_exception_type,
    stop_after_attempt,
    wait_random_exponential,
)

from dm_cli.dmss_api import ApiException
from dm_cli.dmss_api.api.default_api import DefaultApi
from dm_cli.dmss_api.api_client import ApiClient
from dm_cli.dmss_api.exceptions import NotFoundException, ServiceException
from dm_cli.state import state

console = Console()

# The concrete types a request body loaded from JSON is built from.
_JSON_TYPES = frozenset({str, int, float, bool, type(None)})

# Generated response types that are built only from dicts, lists and untyped values, such as
# "object", "Dict[str, object]" and "Dict[str, Optional[object]]".
_PLAIN_JSON_RESPONSE_TYPE = re.compile(r"(?:Dict\[str, |List\[|Optional\[)*object\]*")


class JsonApiClient(ApiClient):
    """An ApiClient that handles plain JSON without the generated type dispatch.

    Most DMSS endpoints take and return documents: arbitrarily nested JSON that the generated client
    describes as "object". It still walks every node of every document on the way in and on the way
    out, which is both slow and, for responses, broken.

    This lives here rather than in dm_cli/dmss_api, because that package is generated by
    'generate-dmss-api.sh' and any edit to it is lost on the next regeneration.
    """

    def sanitize_for_serialization(self, obj):
        """Serialize a request body, dispatching on the concrete type first.

        Request bodies are nested dicts loaded from JSON, and this recurses over every node of every
        document, so it is called millions of times during a package import. The generated
        implementation tests each value against abstract base classes, which is far more expensive
        than an exact type lookup; dispatching on the concrete type first makes it ~3x faster.
        Anything that is not plain JSON still falls through to the generated implementation.
        """
        obj_type = type(obj)
        if obj_type in _JSON_TYPES:
            return obj
        if obj_type is dict:
            return {key: self.sanitize_for_serialization(val) for key, val in obj.items()}
        if obj_type is list:
            return [self.sanitize_for_serialization(item) for item in obj]
        return super().sanitize_for_serialization(obj)

    def deserialize(self, response_text, response_type, content_type):
        """Deserialize a response, returning plain JSON as-is.

        The generated deserializer recurses through a type string such as
        "Dict[str, Optional[object]]" only to hand every leaf to a function that returns it
        unchanged, so collapsing the whole type to "object" is exact and skips the walk. It also
        works around a generator bug: openapi-generator 7.24 emits "Optional[...]" but its own
        deserializer cannot parse it, and raises AttributeError on every successful document_get.
        """
        if isinstance(response_type, str) and _PLAIN_JSON_RESPONSE_TYPE.fullmatch(response_type):
            response_type = "object"
        return super().deserialize(response_text, response_type, content_type)


dmss_api = DefaultApi(api_client=JsonApiClient())


class ApplicationException(Exception):
    status: int = 500
    type: str = "ApplicationException"
    message: str = "The requested operation failed"
    debug: str = "An unknown and unhandled exception occurred in the API"
    data: dict = None

    def __init__(
        self,
        message: str = "The requested operation failed",
        debug: str = "An unknown and unhandled exception occurred in the API",
        data: dict = None,
        status: int = 500,
        type: str = "ApplicationException",
    ):
        self.type = type
        self.status = status
        self.type = self.__class__.__name__
        self.message = message
        self.debug = debug
        self.data = data

    def dict(self):
        return {
            "status": self.status,
            "type": self.type,
            "message": self.message,
            "debug": self.debug,
            "data": self.data,
        }


@retry(
    wait=wait_random_exponential(multiplier=1, max=60),
    stop=stop_after_attempt(5),
    reraise=True,
    retry=retry_if_exception_type(ServiceException),
)
def export(absolute_document_ref: str):
    """Call export endpoint from DMSS to download document(s) as zip.

    The reason dmss_api cannot be used directly is that there were some issues with interpreting the JSON schema,
    which caused the export function in the generated DMSS api to not work properly.
    """
    # Imported lazily; 'requests' is only needed by this command and costs ~200ms to import.
    import requests

    headers = {"Access-Key": state.token}

    response = requests.get(f"{state.dmss_url}/api/export/{absolute_document_ref}", headers=headers)  # nosec
    if response.status_code != 200:
        raise ApplicationException(
            message=f"Could not export document(s) from {absolute_document_ref} (status code {response.status_code})."
        )

    return response


def dmss_exception_wrapper(
    function: Callable,
    *args,
    **kwargs,
) -> Any:
    try:
        return function(*args, **kwargs)
    except ApplicationException as e:
        if state.debug:
            console.print_exception()
        exception = e.dict()
        console.print(exception, style="red1")
        raise typer.Exit(code=1)
    except (NotFoundException, ApiException) as e:
        if state.debug:
            console.print_exception()
        exception = json.loads(e.body)
        console.print(exception, style="red1")
        raise typer.Exit(code=1)
    except Exception as error:
        if state.debug:
            console.print_exception()
        text = Text(str(error))
        console.print(text, style="red1")
        raise typer.Exit(code=1)
