# coding: utf-8

"""
    Data Modelling Storage Service

    API for basic data modelling interaction

    The version of the OpenAPI document: 1.23.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AccessLevel(str, Enum):
    """
    AccessLevel
    """

    """
    allowed enum values
    """
    WRITE = 'WRITE'
    READ = 'READ'
    NONE = 'NONE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccessLevel from a JSON string"""
        return cls(json.loads(json_str))


