# coding: utf-8

"""
    Data Modelling Storage Service

    API for basic data modelling interaction

    The version of the OpenAPI document: 1.23.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dm_cli.dmss_api.models.access_level import AccessLevel
from typing import Optional, Set
from typing_extensions import Self

class PATData(BaseModel):
    """
    PATData
    """ # noqa: E501
    pat_hash: Optional[StrictStr] = None
    uuid: Optional[StrictStr] = '3f89b730-0549-4c7e-b1c4-989c4fabf5a6'
    user_id: StrictStr
    roles: Optional[List[StrictStr]] = None
    scope: AccessLevel
    expire: datetime
    __properties: ClassVar[List[str]] = ["pat_hash", "uuid", "user_id", "roles", "scope", "expire"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PATData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if pat_hash (nullable) is None
        # and model_fields_set contains the field
        if self.pat_hash is None and "pat_hash" in self.model_fields_set:
            _dict['pat_hash'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PATData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pat_hash": obj.get("pat_hash"),
            "uuid": obj.get("uuid") if obj.get("uuid") is not None else '3f89b730-0549-4c7e-b1c4-989c4fabf5a6',
            "user_id": obj.get("user_id"),
            "roles": obj.get("roles"),
            "scope": obj.get("scope"),
            "expire": obj.get("expire")
        })
        return _obj


