# coding: utf-8

"""
    Data Modelling Storage Service

    API for basic data modelling interaction

    The version of the OpenAPI document: 1.28.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RecipeAttribute(BaseModel):
    """
    RecipeAttribute
    """ # noqa: E501
    name: StrictStr
    type: Optional[StrictStr] = 'dmss://system/SIMOS/UiAttribute'
    attribute_type: Optional[StrictStr] = Field(default=None, alias="attributeType")
    label: Optional[StrictStr] = None
    contained: Optional[StrictBool] = True
    var_field: Optional[StrictStr] = Field(default=None, alias="field")
    array_field: Optional[StrictStr] = None
    collapsible: Optional[StrictBool] = None
    ui_recipe: Optional[StrictStr] = None
    mapping: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["name", "type", "attributeType", "label", "contained", "field", "array_field", "collapsible", "ui_recipe", "mapping"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecipeAttribute from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if var_field (nullable) is None
        # and model_fields_set contains the field
        if self.var_field is None and "var_field" in self.model_fields_set:
            _dict['field'] = None

        # set to None if array_field (nullable) is None
        # and model_fields_set contains the field
        if self.array_field is None and "array_field" in self.model_fields_set:
            _dict['array_field'] = None

        # set to None if collapsible (nullable) is None
        # and model_fields_set contains the field
        if self.collapsible is None and "collapsible" in self.model_fields_set:
            _dict['collapsible'] = None

        # set to None if ui_recipe (nullable) is None
        # and model_fields_set contains the field
        if self.ui_recipe is None and "ui_recipe" in self.model_fields_set:
            _dict['ui_recipe'] = None

        # set to None if mapping (nullable) is None
        # and model_fields_set contains the field
        if self.mapping is None and "mapping" in self.model_fields_set:
            _dict['mapping'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecipeAttribute from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "type": obj.get("type") if obj.get("type") is not None else 'dmss://system/SIMOS/UiAttribute',
            "attributeType": obj.get("attributeType"),
            "label": obj.get("label"),
            "contained": obj.get("contained") if obj.get("contained") is not None else True,
            "field": obj.get("field"),
            "array_field": obj.get("array_field"),
            "collapsible": obj.get("collapsible"),
            "ui_recipe": obj.get("ui_recipe"),
            "mapping": obj.get("mapping")
        })
        return _obj


