# coding: utf-8

"""
    Data Modelling Storage Service

    API for basic data modelling interaction

    The version of the OpenAPI document: 1.28.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StorageDataTypes(str, Enum):
    """
    StorageDataTypes
    """

    """
    allowed enum values
    """
    DEFAULT = 'default'
    LARGE = 'large'
    VERYLARGE = 'veryLarge'
    VIDEO = 'video'
    BLOB = 'blob'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StorageDataTypes from a JSON string"""
        return cls(json.loads(json_str))


