on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  release-please:
    needs: tests
    uses: ./.github/workflows/create-release-pr.yaml


  publish-new-pypi-package:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/publish.yaml
    with:
      version: ${{ needs.release-please.outputs.tag_name }}
    secrets:
      PYPI_DM_CLI_TOKEN: ${{ secrets.PYPI_DM_CLI_TOKEN }}