on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v*

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  # TODO remove, only for testing
  release-please:
    needs: tests
    uses: ./.github/workflows/create-release-pr.yaml

