on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v*

jobs:
#  tests:
#    uses: ./.github/workflows/tests.yaml

  # todo remove
  release-please:
    uses: ./.github/workflows/create-release-pr.yaml
