on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  publish:
    needs: tests
    uses: ./.github/workflows/publish.yaml
    secrets:
      PYPI_DM_CLI_TOKEN: ${{ secrets.PYPI_DM_CLI_TOKEN }}

