on:
  workflow_dispatch:
  workflow_call:  # Workflow is meant to be called from another workflow, with the image tag as input
    secrets:
      PYPI_DM_CLI_TOKEN:
        required: true
    inputs:
      version:
        description: "The new package version"
        required: true
        type: string

env:
  VERSION_FILE_PATH: dm_cli/__init__.py

jobs:
  build-n-publish:
    name: Publish dm-cli package to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install wheel and twine
        run: python -m pip install wheel twine
      - name: Delete old version file
        run: rm $VERSION_FILE_PATH
      - name: Create new version file
        run: touch $VERSION_FILE_PATH
      - name: Write new version to version file
        run: echo "VERSION = '${{ inputs.version }}'" >> $VERSION_FILE_PATH
      - name: build pypi package
        run: python3 setup.py sdist bdist_wheel
      - name: Publish pacakge to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_DM_CLI_TOKEN }}
        run: python -m twine upload dist/*