on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: install requirements
        run: pip install -r requirements.txt && pip install -r dev-requirements.txt && pip install .

      - name: run pytest
        run: pytest