on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: install requirements
        run: pip install -r requirements.txt && pip install -r dev-requirements.txt && pip install -e .

      - name: run pytest
        run: pytest

  integration-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/integration
    steps:
      - uses: actions/checkout@master

      - name: Start DMSS
        run: docker-compose up -d && sleep 60 && docker-compose run --rm dmss reset-app

      - name: Download test blueprints
        run: |
          npm pack @development-framework/dm-core-plugins
          tar -xzf development-framework-dm-core-plugins-*.tgz

      - name: Build and install dm-cli package
        run: |
          cd ../..
          python -m venv .venv
          source .venv/bin/activate
          pip install wheel twine
          python setup.py sdist bdist_wheel
          pip install ./dist/dm-cli-*.tar.gz

      - name: Tests
        run: |
          source ../../.venv/bin/activate
          dm reset ../test_data/test_app_dir_struct
          dm import-plugin-blueprints ../test_data/plugins_example
          dm create-lookup test DemoApplicationDataSource/models/recipe_links DemoApplicationDataSource/models/more_recipe_links
          dm export DemoApplicationDataSource/models/CarPackage
          dm export DemoApplicationDataSource/instances --unpack
          dm ds import ../test_data/test_app_dir_struct/data_sources/DemoApplicationDataSource.json
          dm ds import-all ../test_data/test_app_dir_struct/data_sources
          dm entities import ../test_data/more_documents/bmw.json DemoApplicationDataSource/instances
          dm entities import ../test_data/more_documents/engines DemoApplicationDataSource/instances
          dm entities delete DemoApplicationDataSource/instances
          dm ds reset DemoApplicationDataSource ../test_data/test_app_dir_struct
          dm ds init ../test_data/test_app_dir_struct