on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: install requirements
        run: pip install -r requirements.txt && pip install -r dev-requirements.txt && pip install .

      - name: run pytest
        run: pytest

  integration-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/integration
    steps:
      - uses: actions/checkout@master

      - name: Start DMSS
        run: docker-compose up -d && sleep 60 && docker-compose run --rm dmss reset-app

      - name: Download test blueprints
        run: |
          npm pack @development-framework/dm-core-plugins
          tar -xzf development-framework-dm-core-plugins-*.tgz

      - name: Setup python
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -e ../..

      - name: Tests
        run: |
          pip install -e ../..
          dm reset ../test_data/test_app_dir_struct
          dm import-plugin-blueprints package
          dm create-lookup test DemoApplicationDataSource/instances