# coding: utf-8

"""
    Data Modelling Storage Service

    API for basic data modelling interaction  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from dmss_api import schemas  # noqa: F401


class RepositoryType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An enumeration.
    """


    class MetaOapg:
        enum_value_to_name = {
            "mongo-db": "MONGODB",
            "azure-blob-storage": "AZUREBLOBSTORAGE",
            "localStorage": "LOCAL_STORAGE",
        }

    @schemas.classproperty
    def MONGODB(cls):
        return cls("mongo-db")

    @schemas.classproperty
    def AZUREBLOBSTORAGE(cls):
        return cls("azure-blob-storage")

    @schemas.classproperty
    def LOCAL_STORAGE(cls):
        return cls("localStorage")
